### ISSUE TITLE
Windows 7中Vim 8下不正常

### ISSUE THREAD

**Issue by deathrush** [m8524769/Hybrid-fonts#1]
![image 5](https://user-images.githubusercontent.com/10840992/34549008-6d6ad956-f140-11e7-9f2f-75adbff568ec.png)

**Comment by m8524769** [comment]
OK, 我去看下。。

**Comment by m8524769** [comment]
再试一下
[DejaVu #1.zip](https://github.com/m8524769/Hybrid-fonts/files/1609483/DejaVuSansMono.YaHei.NF.1.zip)

**Comment by deathrush** [comment]
比原来好多了，但是汉字之间的宽度还是过大
![image](https://user-images.githubusercontent.com/10840992/34662268-516cc5b4-f48a-11e7-84e5-ff7914045657.png)

对比Microsoft Yahei Mono，英文字貌似较大：
![tim 20180108154232](https://user-images.githubusercontent.com/10840992/34662297-91eabe16-f48a-11e7-935c-37c8f6ba661c.jpg)

**Comment by m8524769** [comment]
@deathrush 
- 首先感谢你的反馈 :smile: 
- 是这样的，Microsoft YaHei Mono 的西文部分用的是 Consolas，而 DejaVu Sans Mono 本身就比其宽大一些，这样也导致了 DejaVu 宽度的两倍大于其中文雅黑部分，Vim 中字符是垂直对齐的，从而增大了汉字字距。这也是为什么 Consolas 能够更好的契合微软雅黑。
- 其实增大字体可以略微改善体验。
- 另外，我的字体中的中文标点符号并不是截图中的这样，我可以看下你的配置么？

**Comment by deathrush** [comment]
不好意思，之前是通过`:set gfn=*`来设置的。
vimrc设置`set guifont+=DejaVuSansMono\ YaHei\ NF:h10,`的效果：
![image](https://user-images.githubusercontent.com/10840992/34703561-8ab00238-f52e-11e7-8336-4da48b7daefa.png)

**Comment by deathrush** [comment]
现在的vimrc字体设置：
```
if has("gui_win32")
    set guifont+=DejaVuSansMono\ YaHei\ NF:h10,
    set guifont+=Microsoft\ Yahei\ Mono:h10,
    set guifont+=等距更纱黑体\ SC:h10, "相对比较窄
    set guifont+=Gen\ Shin\ Gothic\ Monospace\ Regul:h10,
    set guifont+=幼圆:h10:b, "Windows平台默认自带
endif
```
官方编译的Vim 8中guifontwide已不再支持非等宽的中文字体了，所以只能使用等宽的中文字体，数量非常少，非常感谢M大制作这个混合字体。

**Comment by m8524769** [comment]
哈哈很高兴你能喜欢 :smiley:
