### ISSUE TITLE
在 Sublime 上无法成功设置字体

### ISSUE THREAD

**Issue by wadecoding** [m8524769/Hybrid-fonts#2]
嗨，非常感谢你做的字体。但是我在尝试这些字体的时候遇到了点麻烦。

我试了 `FiraCode QiHei NF` 和 `DejaVuSansMono YaHei NF` 这两款字体。但在 Sublime 中指定 `font_face` 的时候它们都不起作用。不知道是怎么回事，你能帮我看一下吗

我的 Sublime 配置文件如下，使用字体的版本是
`DejaVuSansMono YaHei NF`: 2.43
`FiraCode QiHei NF`: 1.22

```
{
  "font_face": "DejaVuSansMono YaHei NF",
  "font_size": 14,
  "ignored_packages":
  [
    "Vintage"
  ],
  "ignored_words":
  [
    "analyse"
  ]
}
```

**Comment by m8524769** [comment]
@wadecoding 你重启一下电脑试试？我这边也是一样的，安装完不会立即生效（只有 sublime 会这样）。Linux 系统的话执行 `fc-cache -fv` 刷新字体缓存就行了。

**Comment by a1waysbeta** [comment]
借楼求助一下，请问博主对fontlink 有了解么？sublime字体链接我一直设置不起作用

**Comment by wadecoding** [comment]
我把字体更新之后重启又试了一下，发现 `DejaVuSansMono YaHei NF` 工作正常，但是 `FiraCode QiHei NF` 还是不能正常工作。不过我本来就是想用 `DejaVuSansMono YaHei NF` 这个字体的。问题解决了，非常感谢 :grin:
