### ISSUE TITLE
InconsolataGo QiHei NF "-" display as "─"

### ISSUE THREAD

**Issue by chenzaichun** [m8524769/Hybrid-fonts#3]
![image](https://user-images.githubusercontent.com/127616/91863803-15a1be00-eca2-11ea-8dab-ded2ecadd98a.png)

**Comment by m8524769** [comment]
@chenzaichun 你好，
截图里的横杠可能不是减号而是一种制表符，你可以试试输入一连串减号看看有没有问题，我这边试了一下并没有发现问题。。

**Comment by chenzaichun** [comment]
好象是这样的，在orgmode中，'-' 会被替换为 "─". 但是其他字体看不出来，比如”Sarasa Mono SC Nerd“。

InconsolataGo QiHei NF能做到严格的等宽等高吗？强迫症有点验证，不等到，在输入中英文的时候会造成行下层。

**Comment by m8524769** [comment]
@chenzaichun 刚看了一下，InconsolataGo 这个字体本身并不包含 "─" 等一系列制表符，因此是沿用了中文部分的字符，所以你会看到宽度变成了两倍，另外，输入中文时下沉的问题我这边没有复现，你用的是Emacs吗？

**Comment by chenzaichun** [comment]
是的，我用的Emacs。能否加入英文的 `-` 制表符?

字体有一点点下沉，见截图

![Peek 2020-09-04 10-09](https://user-images.githubusercontent.com/127616/92191682-fa4bd400-ee96-11ea-94e2-b4294cc1a9ea.gif)

**Comment by m8524769** [comment]
@chenzaichun 好的，非常感谢你的反馈，我这边尽快修复

**Comment by chenzaichun** [comment]
@m8524769 感谢。

还有一点，感觉上中英文的字重不太一致。比如 `Sarasa Mono SC Nerd` 看起来中英文字重比较一致。

![image](https://user-images.githubusercontent.com/127616/92316238-c520bc80-f023-11ea-8701-885aac3a2de2.png)

`InconsolateGo QiHei NF` 效果如下：

![image](https://user-images.githubusercontent.com/127616/92316256-f39e9780-f023-11ea-9cf2-e7921bfc47e6.png)

**Comment by m8524769** [comment]
@chenzaichun 你先检查一下字体设置有没有问题，我看截图里的中文字体更类似圆体而非黑体，我放个截图你可以对比一下：

![sample](https://user-images.githubusercontent.com/23133604/92319452-e34de300-f04a-11ea-9140-9de4744cbd78.png)

**Comment by chenzaichun** [comment]
很奇怪的问题，我在 `spacemacs` 里面设置字体为 `InConsolataGo QiHei NF` 之后，中文他默认使用的是 `Youyuan`， 并不是旗黑。我指定中文字体为 `InConsolataGo QiHei NF` 之后的效果如下:
![image](https://user-images.githubusercontent.com/127616/92320368-860a5f80-f053-11ea-9b9d-9d3a12e8de0f.png)
这样貌似没有下沉的情况了。但是感觉字重还是不太一致。

**Comment by m8524769** [comment]
@chenzaichun 你试下这个：[InconsolataGo QiHei NF #3.zip](https://github.com/m8524769/Hybrid-fonts/files/5179944/InconsolataGo.QiHei.NF.3.zip)

主要有两个改动：
1. 添加了与西文等宽的制表符
2. 汉仪旗黑由 55S 替换为了 50S

**Comment by chenzaichun** [comment]
看起来很不错
![image](https://user-images.githubusercontent.com/127616/92340921-a20f0f00-f0ee-11ea-8eb8-fc1e386fef26.png)

![image](https://user-images.githubusercontent.com/127616/92340895-8d327b80-f0ee-11ea-8e53-639b57c7eb2e.png)
能麻烦提供一下 `bold` 和 `italic` 的版本吗？ 谢谢。

**Comment by m8524769** [comment]
@chenzaichun 那两个还没弄，估计这两天能肝出来，稍安勿躁

**Comment by m8524769** [comment]
@chenzaichun 斜体已经弄好了，顺便修了点bug，[InconsolataGo QiHei NF #4.zip](https://github.com/m8524769/Hybrid-fonts/files/5185613/InconsolataGo.QiHei.NF.4.zip)

粗体的话你用之前的版本应该没什么问题

**Comment by chenzaichun** [comment]
感谢。
